name: g
description: g flutter package with global functions
version: 0.0.1
repository: https://github.com/hkloudou/darts/tree/main/g


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_size_text_pk: ^3.0.0
  flutter:
    sdk: flutter
  universal_platform: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0